services:
  - type: web
    name: chat-hub-ui
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUM_MODEL
        value: gpt-4o-mini